<?php
/**
 * Novalnet Subscription extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet Subscription extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Subscription
 * @copyright  Copyright (c) Novalnet AG
 */
$collection = $block->getCollection();
$viewUrl = $block->getUrl('novalnet_subscription/subscription/view');
?>
<?php if ($collection && count($collection)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="recurring-profiles-list">
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= /* @noEscape */ $block->escapeHtml(__('Reference ID #')) ?></th>
                    <th scope="col" class="col actions"><?= /* @noEscape */ $block->escapeHtml(__('Created At')) ?></th>
                    <th scope="col" class="col actions"><?= /* @noEscape */ $block->escapeHtml(__('Payment Method')) ?></th>
                    <th scope="col" class="col actions"><?= /* @noEscape */ $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($collection as $item): ?>
                    <tr>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Reference ID #')) ?>" class="col id"><?= /* @noEscape */ $block->escapeHtml($item->getSubscriptionId()) ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Created At')) ?>" class="col id"><?= /* @noEscape */ $block->escapeHtml($block->getHelper()->getDate($item->getCreatedAt(), 'm/d/y')) ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Payment Method')) ?>" class="col id"><?= /* @noEscape */ $block->getPaymentTitleByCode($item->getPaymentMethod()) ?></td>
                        <td data-th="<?= /* @noEscape */ $block->escapeHtml(__('Reference ID #')) ?>" class="col id"><a href="<?= /* @noEscape */ $viewUrl.'id/'.$item->getId() ?>"><?= /* @noEscape */ __('View') ?></a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?= /* @noEscape */ __('No Profiles found') ?></span></div>
<?php endif ?>
