<?php
/**
 * Novalnet Subscription extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet Subscription extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Subscription
 * @copyright  Copyright (c) Novalnet AG
 */
$collection = $block->getCollection();
$hash = $block->getLocationHash();
$formattedAddress = $block->getFormattedAddress();
$order = $block->getOrder();
$paymentCode = $block->getCollectionData('payment_method');
$profileId = $block->getRequest()->getParam('id');
?>
<ul class="tab items order-links" data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 1, "disabled": [2], "disabledState": "disabled"}}'>
    <li class="nav item tablinks <?= /* @noEscape */ ($hash == 'profile_details') ? 'active' : '' ?>" onclick="infofunc(event, 'profile_details')" title="<?=  /* @noEscape */__('Related orders') ?>">
        <a> <?= /* @noEscape */ __('Profile Information') ?></a>
    </li>
    <li class="nav item tablinks <?= /* @noEscape */ ($hash == 'related_orders') ? 'active' : '' ?>" onclick="infofunc(event, 'related_orders')" title="<?= /* @noEscape */ __('Related orders') ?>">
        <a> <?= /* @noEscape */ __('Related orders') ?></a>
    </li>
</ul>
<hr style="margin: 0 0 35px 0;">
<section class="profile_view_section">
<div id="profile_details" class="tabcontent" style="<?= /* @noEscape */ ($hash == 'profile_details') ? 'display:block' : 'display:none' ?>"><br />
    <div class="block block-order-details-view">
        <div class="block-content">
            <div class="box box-information profile-reference" style="width:50%">
                <strong class="box-title"><span><?= /* @noEscape */ __('Reference') ?></span></strong>
                <div class="box-content">
                    <table class="nn-subscription-table">
                        <tbody>
                            <tr>
                                <th class="col label"><?= /* @noEscape */ __('Payment Method') ?></th>
                                <td class="col data"><?= /* @noEscape */ $block->getPaymentTitleByCode($paymentCode) ?></td>
                            </tr>
                            <tr>
                                <th class="col label"><?= /* @noEscape */ __('Reference ID') ?></th>
                                <td class="col data"><?= /* @noEscape */ $block->getCollectionData('subscription_id') ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <?php if (!$order->getIsVirtual()) { ?>
                <div class="box box-order-billing-address">
                    <strong class="box-title">
                        <span><?= /* @noEscape */ __('Billing Address') ?></span>
                    </strong>
                    <div class="box-content">
                        <?= /* @noEscape */ $formattedAddress['billing']; ?>
                    </div>
                </div>
                <div class="box box-order-shipping-address">
                    <strong class="box-title">
                        <span><?= /* @noEscape */ __('Shipping Address') ?></span>
                    </strong>
                    <div class="box-content">
                        <?= /* @noEscape */ $formattedAddress['shipping'];  ?>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
    <div class="block">
        <div class="block-content">
            <div class="box box-information" style="width:100%">
                <strong class="box-title"><?= /* @noEscape */ __('PURCHASED ITEM(s)') ?></strong>
                <div class="box-content">
                    <table style="font-size:14px" class="data table">
                        <thead>
                            <tr class="headings">
                                <th class="col-product"><span><?= /* @noEscape */ __('Name') ?></span></th>
                                <th class="col-ordered-qty"><span><?= /* @noEscape */ __('Qty') ?></span></th>
                                <th class="col-subtotal"><span><?= /* @noEscape */ __('Billing Period') ?></span></th>
                                <th class="col-subtotal"><span><?= /* @noEscape */ __('Billing Information') ?></span></th>
                                <th class="col-tax-amount"><span><?= /* @noEscape */ __('Status') ?></span></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($block->getOrderItemDetails() as $id => $item) { ?>
                                <?php
                                    $state = $item['state'];
                                    $url = ($state == 'ACTIVE') ? $block->getCancelUrl() : $block->getActivateUrl();
                                    $stateClass = ($state == 'ACTIVE') ? 'notice' : (($state == 'CANCELED') ? 'critical' : (($state == 'EXPIRED') ? 'critical' : 'minor'));
                                ?>
                                <tr>
                                    <td class="col-product-name">
                                        <?= /* @noEscape */ $item['Name'] ?>
                                    </td>
                                    <td class="col-qty" style="width:50px">
                                        <?= /* @noEscape */ $item['Qty'] ?>
                                    </td>
                                    <td class="col-billing-details">
                                        <?= /* @noEscape */ $item['BillingDetails'] ?>
                                    </td>
                                    <td class="col-billing-details">
                                        <?= /* @noEscape */ $item['BillingInformation'] ?>
                                    </td>
                                    <td class="col-billing-amount" style="width:170px">
                                        <span class="grid-severity-<?= /* @noEscape */ $stateClass ?>"><?= /* @noEscape */ __($state) ?></span>
                                    </td>
                                    <?php if ($state == 'ACTIVE' && $block->canCancel()) { ?>
                                        <td class="col-cancel" style="width:120px">
                                            <button data-url="<?= /* @noEscape */ $url.$id ?>" class="sub-cancel"><?= /* @noEscape */ __('CANCEL') ?></button>
                                        </td>
                                    <?php } ?>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="related_orders" class="tabcontent" style="<?= ($hash == 'related_orders') ? 'display:block' : 'display:none' ?>">
    <table class="data table">
        <thead>
            <tr>
                <th class="col"><?= /* @noEscape */ __('Order #') ?></th>
                <th class="col"><?= /* @noEscape */ __('Date') ?></th>
                <th class="col"><?= /* @noEscape */ __('Customer Name') ?></th>
                <th class="col"><?= /* @noEscape */ __('Order Total') ?></th>
                <th class="col"><?= /* @noEscape */ __('Status') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getRelatedOrderCollection() as $item) { ?>
                <tr>
                    <td class="col"><a href="<?= /* @noEscape */ $block->getUrl('sales/order/view/').'order_id/'.$item->getEntityId() ?>"><?= /* @noEscape */ $item->getIncrementId() ?></a></td>
                    <td class="col"><?= /* @noEscape */ $block->getHelper()->getDate($item->getCreatedAt(), 'm/d/y') ?></td>
                    <td class="col"><?= /* @noEscape */ $item->getCustomerName() ?></td>
                    <td class="col"><?= /* @noEscape */ $block->pricingHelper->currency($item->getGrandTotal(), true, false) ?></td>
                    <td class="col"><?= /* @noEscape */ $item->getStatus() ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
<?php endif; ?>
</div>

<script>
function infofunc(evt, cityName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(cityName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>
<script>
require([
    "jquery",
    "Magento_Ui/js/modal/alert"
    ], function($, alert){
        $('.sub-cancel').click(function(){
            if(confirm("<?= /* @noEscape */ __('Are you sure you want to cancel?') ?>")) {
                var requestURL = $(this).attr('data-url');
                $('body').trigger('processStart');
                $.ajax({
                    url: requestURL,
                    type: 'GET',
                    dataType: 'json',
                    success: function(response) {
                        window.location = window.location.hash ;
                        location.reload();
                    },
                    error: function(response) {
                        $('body').trigger('processStop');
                        alert({
                            content: "<?= /* @noEscapes */__('Please try again later') ?>"
                        });
                    }
                });
            }
        });
    });
</script>
</section>
<style>
.order-links .item.active a {
    background: #fff;
}
.order-links .item a {
    border-bottom:unset;
}
</style>
