<?php
/**
 * Novalnet Subscription extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet Subscription extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Subscription
 * @copyright  Copyright (c) Novalnet AG
 */
$profile = $block->getProfile();
$order = $block->getOrder();
$billingAddress = $order->getBillingAddress();
$shippingAddress = $order->getShippingAddress();
$formattedAddress = $block->getFormattedAddress();
$orderItems = $block->getOrderItemDetails();
$order = $block->getOrder();
$pauseUrl = $block->getPauseUrl();
$cancelUrl = $block->getCancelUrl();
$activateUrl = $block->getActivateUrl();
?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-title">
                    <span class="title">
                        <?= /* @noEscape */ __('Profile # %1', $profile->getReferenceTid()) ?>
                    </span>
                </div>
                <div class="admin__page-section-item-content">
                    <table class="admin__table-secondary order-information-table">
                        <tbody>
                            <tr>
                                <th><?= /* @noEscape */ __('Reference ID') ?></th>
                                <td><?= /* @noEscape */ $profile->getSubscriptionId() ?></td>
                            </tr>
                            <tr>
                                <th><?= /* @noEscape */ __('Payment Method') ?></th>
                                <td><?= /* @noEscape */ $block->getPaymentTitleByCode($profile->getPaymentMethod()) ?></td>
                            </tr>
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
</section>
<?php if (!$order->getIsVirtual()) { ?>
    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __('Address Information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @noEscape */ __('Billing Address') ?></span>
                </div>
                <?= /* @noEscape */ $formattedAddress['billing']; ?>
            </div>
            <div class="admin__page-section-item order-shipping-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @noEscape */ __('Shipping Address') ?></span>
                </div>
                <?= /* @noEscape */ $formattedAddress['shipping'];  ?>
            </div>
        </div>
    </section>
<?php } ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Ordered Items') ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
                <tr class="headings">
                    <th class="col-product"><span><?= /* @noEscape */ __('Name') ?></span></th>
                    <th class="col-ordered-qty"><span><?= /* @noEscape */ __('Qty') ?></span></th>
                    <th class="col-ordered-qty"><span><?= /* @noEscape */ __('Status') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @noEscape */ __('Billing Period') ?></span></th>
                    <th class="col-subtotal"><span><?= /* @noEscape */ __('Billing Information') ?></span></th>
                    <th class="col-tax-amount"><span><?= /* @noEscape */ __('Action') ?></span></th>
                </tr>
            </thead>
            <tbody class="even">
                <?php foreach ($block->getOrderItemDetails() as $id => $item) { ?>
                    <?php
                        $state = $item['state'];
                        $url = ($state == 'ACTIVE') ? $cancelUrl : (($state == 'PAUSED') ? $activateUrl : '');
                        $text = ($state == 'ACTIVE') ? __('CANCEL') : (($state == 'PAUSED') ? __('REACTIVATE') : '');
                        $stateClass = ($state == 'ACTIVE') ? 'notice' : (($state == 'CANCELED') ? 'critical' : (($state == 'EXPIRED') ? 'critical' : 'minor'));
                        $msg = ($state == 'ACTIVE') ? __('cancel') : (($state == 'PAUSED') ? __('reactivate') : '');
                    ?>
                    <tr>
                        <td class="col-product-name">
                            <?= /* @noEscape */ $item['Name'] ?>
                        </td>
                        <td class="col-qty">
                            <?= /* @noEscape */ $item['Qty'] ?>
                        </td>
                        <td class="col-qty">
                            <span class="grid-severity-<?= /* @noEscape */ $stateClass ?>"><?= /* @noEscape */ __($state) ?></span>
                        </td>
                        <td class="col-billing-details">
                            <?= /* @noEscape */ $item['BillingDetails'] ?>
                        </td>
                        <td class="col-billing-details">
                            <?= /* @noEscape */ $item['BillingInformation'] ?>
                        </td>
                        <td class="col-cancel">
                            <?php if ($state == 'PAUSED') { ?>
                                <div class="control">
                                    <?=
                                        $block->getLayout()->createBlock(\Magento\Framework\View\Element\Html\Date::class)
                                            ->setData([
                                                'name' => 'date',
                                                'id' => 'date',
                                                'class' => 'admin__control-text next_schedule',
                                                'date_format' => 'dd-MM-y',
                                                'image' => $block->getViewFileUrl('Magento_Theme::calendar.png'),
                                                'years_range' => '-120y:c+nn',
                                                'change_month' => 'true',
                                                'change_year' => 'true',
                                                'show_on' => 'both',
                                                'first_day' => 1,
                                                'required' => 'true'
                                            ])
                                        ->toHtml()
                                    ?>
                                </div>
                                <label class="admin__field-error date-error" style="display:none"><?= /* @noEscape */ __('This is a required field') ?>.</label></br>
                            <?php } ?>
                            <button
                            data-msg="<?= /* @noEscape */ __('Are you sure you want to %1?', $msg) ?>"
                             data-url="<?= /* @noEscape */ $url.$id ?>" class="sub-cancel" <?= empty($text) ? 'disabled' : '' ?>><?= /* @noEscape */ !empty($text) ? $text : __('REACTIVATE') ?></button>
                            <?php if ($state == 'ACTIVE') { ?>
                                <button
                                data-msg="<?= /* @noEscape */ __('Are you sure you want to pause?') ?>"
                                 data-url="<?= /* @noEscape */ $pauseUrl.$id ?>" class="sub-cancel"><?= /* @noEscape */ __('PAUSE') ?></button>
                            <?php } ?>
                        </td>
                    </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</section>
<script>
require([
    "jquery",
    "Magento_Ui/js/modal/alert"
    ], function($, alert){
        $('.sub-cancel').click(function(e) {
            var msg = $(this).attr('data-msg');
            var nextSchedule = '';
            var requestURL = $(this).attr('data-url');
            <?php if ($state == 'PAUSED') { ?>
                nextSchedule = $('.next_schedule').val();
                if (nextSchedule == '') {
                    $('.date-error').show();
                    e.stopPropagation();
                    return;
                } else {
                    $('.date-error').hide();
                }
                requestURL = requestURL+'/'+nextSchedule;
            <?php } ?>

            if(confirm(msg)) {
                $('body').trigger('processStart');
                $.ajax({
                    url: requestURL,
                    type: 'GET',
                    dataType: 'json',
                    success: function(response) {
                        location.reload();
                    },
                    error: function(response) {
                        $('body').trigger('processStop');
                        alert({
                            content: "<?= /* @noEscapes */__('Please try again later') ?>"
                        });
                    }
                });
            }
        });
    });
</script>
