<?php
/**
 * Novalnet Subscription extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet Subscription extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Subscription
 * @copyright  Copyright (c) Novalnet AG
 */
?>

<script>
    require([
        'jquery'
    ], function ($) {
        var products = $('.item.product.product-item');

        products.each(function () {
            var product = $(this);
            var productImg = product.find('.product-image-wrapper'),
                labelEl = product.find('.nnsubscription-label');

            if (!productImg.length) {
                productImg = product.find('.product.photo.product-item-photo');
            }

            productImg.css({'overflow': 'unset'});
            productImg.append(labelEl);

            labelEl.show();
        })
    });
</script>
