<?php
/**
 * Novalnet Subscription extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Novalnet End User License Agreement
 * that is bundled with this package in the file LICENSE.txt
 *
 * DISCLAIMER
 *
 * If you wish to customize Novalnet Subscription extension for your needs,
 * please contact technic@novalnet.de for more information.
 *
 * @category   Novalnet
 * @package    Novalnet_Subscription
 * @copyright  Copyright (c) Novalnet AG
 */
$product = $block->getProduct();
$recurringOptions = json_decode($product->getNovalnetRecurringOptions(), true);
$showRegular = $product->getNovalnetRecurringMethod();
?>
<?php if ($product->getNovalnetSubEnabled()): ?>
    <h4><?= /* @noEscape */ __('Billing Period') ?></h4>
    <div class="recurring_profile_options">
        <ul>
            <?php if (is_array($recurringOptions) && count($recurringOptions) > 0) {
                $i = 1;
                foreach ($recurringOptions as $option) {
                    $activeClassName = ($showRegular == 'subscription_only' && $i == 1) ? 'active' : '';
                    $checkedClassName = ($showRegular == 'subscription_only' && $i == 1) ? 'checked' : ''; ?>
                    <li class="<?= /* @noEscape */ $activeClassName ?>">
                        <input type="radio" name="recurring_option" id="recurring_option_<?= /* @noEscape */ $option['record_id'] ?>" value='<?= /* @noEscape */ $option['record_id'] ?>' data-validate="{required: true}" <?= /* @noEscape */ $checkedClassName ?>>
                        <label for="recurring_option_<?= /* @noEscape */ $option['record_id'] ?>">
                            
                            <?php if (!empty($option['maximum_billing_frequency'])): ?>
                                <?= /* @noEscape */ __('Recurrs %1 time(s)', $option['maximum_billing_frequency']) ?>
                                <?= /* @noEscape */ __('Every %1', $option['billing_frequency']) . ' ' .__($option['period_unit'])?>
                            <?php else: ?>
                                <?= /* @noEscape */ __('Every %1', $option['billing_frequency']) . ' ' .__($option['period_unit'])?>
                                <p><?= /* @noEscape */ __('Repeats until cancelled') ?></p>
                            <?php endif; ?>
                        </label>
                    </li>
                <?php $i++;}
            }
            if ($showRegular != 'subscription_only') { ?>
                <li>
                    <input type="radio" name="recurring_option" id="regular_payment" value="regular_payment" checked data-validate="{required: true}">
                    <label for="regular_payment"><?= /* @noEscape */ __('Single Purchase') ?></label>
                </li>
            <?php } ?>
        </ul>
    </div>
    <?php if (!empty($product->getNovalnetSubTrialPeriodUnit()) && !empty($product->getNovalnetSubTrialPeriodFrequency())): ?>
        <h4><?= /* @noEscape */ __('Trial Period') ?></h4>
        <p><?= /* @noEscape */ __($product->getNovalnetSubTrialPeriodFrequency()).' '. __($product->getNovalnetSubTrialPeriodUnit()).' '. __('cycle')?></p>
    <?php endif; ?>
    <?php if (!empty($product->getNovalnetSubInitialFee())): ?>
        <h4><?= /* @noEscape */ __('Initial Fee') ?></h4>
        <p><?= /* @noEscape */ $this->helper(Magento\Framework\Pricing\Helper\Data::class)->currency($product->getNovalnetSubInitialFee(), true, false); ?></p>
    <?php endif; ?>
<?php endif; ?>
<style>
.recurring_profile_options li {
    list-style:none;
    margin-bottom:15px;
}
.recurring_profile_options ul {
    padding-left:unset;
}
.recurring_profile_options li {
    display: block;
    justify-content: space-between;
    box-sizing: border-box;
    padding: 10px;
    width: 100%;
    border-radius: 2px;
    background: #f9f9f9;
    cursor: pointer;
}
.recurring_profile_options li.active {
    border: 1px solid;
}
.recurring_profile_options li:hover {
    box-shadow: 0 2px 8px rgb(56 77 108 / 40%);
}
</style>
<script>
require([
    "jquery",
    "Magento_Ui/js/modal/alert"
    ], function($, alert){
        $('.recurring_profile_options li').click(function(){
            $('.recurring_profile_options li.active').removeClass('active');
            $(this).addClass('active');
            $(this).find('input[name="recurring_option"]').attr('checked', true);
        });
    });
</script>
